# Generated by Django 5.0.3 on 2024-07-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salle', '0002_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contact',
        ),
    ]
