# Generated by Django 5.0.3 on 2024-07-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salle', '0003_rename_contactus_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
